apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: bWFya2V0aW5nX3VzZXI=
  POSTGRES_PASSWORD: c3Ryb25nX3Bhc3N3b3JkXzEyMw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_DB: "marketing_db"
  DB_HOST: "db-service"
  DB_PORT: "5432"
  CSV_PATH: "/data/marketing_campaigns.csv"