apiVersion: batch/v1
kind: Job
metadata:
  name: data-loader-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: loader
        image: marketing-roi-app:v1
        imagePullPolicy: Never
        command: ["python", "loader.py"]
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"